In [ ]:
import zipfile
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
pwd

'/content'

In [ ]:
cd drive/MyDrive/BrainSignals/

/content/drive/MyDrive/BrainSignals


In [ ]:
import load_data

BATCH_SIZE =84420
# return DataSet class
data = load_data.read_data_sets(one_hot=False)

# get train data and labels by batch size
train_x, train_label = data.train.next_batch(BATCH_SIZE)
# get test data
test_x = data.test.data

# get test labels
test_label = data.test.labels

# get sample number
n_samples = data.train.num_examples
print(n_samples)


84420


In [ ]:
print(data.train.epochs_completed)
train_x, train_label = data.train.next_batch(BATCH_SIZE)

print(train_x.shape)
print(train_label.shape)
X_train = train_x
Y_train = train_label

X_test = test_x
Y_test = test_label


0
(84420, 310)
(84420,)


In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=100)# adjust yourself
pca.fit(train_x)
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)
print(X_train.shape)

print(type(X_train))

(84420, 100)
<class 'numpy.ndarray'>


In [ ]:
!pip install Cython
!pip3 install pymrmre

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 9.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pymrmre: filename=pymrmre-1.0.7-cp39-cp39-linux_x86_64.whl size=408614 sha256=9f31770ab8d07bc119a07f6f90cf3a76021d77a540234a19535e079abae2dce0
  Stored in directory: /root/.cache/pip/wheels/6f/a0/83/77e470a95cfdc1d7ba3079e58cc9ed39b2118936f264c96617
Successfully built pymrmre


In [ ]:
from pymrmre import mrmr
import pandas as pd
import numpy as np 


train_x = pd.DataFrame(train_x) 
train_label = pd.DataFrame(train_label)

mu, sigma = 0, 0.1 
noise = np.random.normal(mu, sigma, [2,2])

train_x=train_x.add_prefix('f')
print(train_x)
solutions = mrmr.mrmr_ensemble(features=train_x,targets=train_label,solution_length=90,solution_count=3).to_numpy()

              f0         f1         f2         f3         f4         f5  \
0      26.806091  26.866707  26.501648  25.566511  25.193199  27.874976   
1      26.614203  26.814353  26.979892  25.490977  26.379157  27.025772   
2      24.265662  24.258697  25.145599  24.239400  24.156880  24.858392   
3      24.538697  24.767115  25.294580  24.065448  24.584059  25.082566   
4      25.833926  25.671698  25.565475  25.123262  24.892601  26.204494   
...          ...        ...        ...        ...        ...        ...   
84415  26.376381  26.018134  25.951905  25.464171  24.961938  26.688813   
84416  25.481061  25.340918  25.460429  24.632501  24.683716  25.942102   
84417  27.328086  28.052501  27.159021  26.007431  26.288843  27.848905   
84418  25.109914  24.903373  25.187650  24.476838  24.206152  25.633163   
84419  24.757580  24.745625  25.554893  24.747519  24.605078  24.700008   

              f6         f7         f8         f9  ...       f300       f301  \
0      26.456464  2

/usr/local/lib/python3.9/dist-packages/pymrmre/MrmreData.py:19: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  self._feature_types  = pd.Series()
/usr/local/lib/python3.9/dist-packages/pymrmre/MrmreData.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  self._strata         = pd.Series()
/usr/local/lib/python3.9/dist-packages/pymrmre/MrmreData.py:21: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  self._weights        = pd.Series()
/usr/local/lib/python3.9/dist-packages/pymrmre/MrmreFilter.py:24: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence t



```
# Model 1
```



In [ ]:
from sklearn import svm
model1 = svm.SVC()
model1.fit(train_x, train_label.values.ravel())

SVC()

In [ ]:
print(model1)
result1 = model1.predict(test_x)

SVC()


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [ ]:
model2 = svm.SVC()
model2.fit(train_x, train_label.values.ravel())

SVC()

In [ ]:
model3 = svm.SVC()
model3.fit(train_x, train_label.values.ravel())

SVC()

In [ ]:
result2 = model2.predict(test_x)
result3 = model3.predict(test_x)


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

print("Model - 1")
cm1 = confusion_matrix(Y_test, result1)
acc1=accuracy_score(Y_test, result1)
cm2 = confusion_matrix(Y_test, result2)
acc2=accuracy_score(Y_test, result2)
cm3 = confusion_matrix(Y_test, result3)
acc3=accuracy_score(Y_test, result3)
print(cm1)
print(acc1)
print("Model - 2")
print(cm2)
print(acc2)
print("Model - 3")
print(cm3)
print(acc3)

Model - 1
[[ 8429  8012  1997]
 [ 1901 17011   828]
 [ 1107  1051 17792]]
0.74373795761079
Model - 2
[[ 8429  8012  1997]
 [ 1901 17011   828]
 [ 1107  1051 17792]]
0.74373795761079
Model - 3
[[ 8429  8012  1997]
 [ 1901 17011   828]
 [ 1107  1051 17792]]
0.74373795761079


In [ ]:
print("Average accuracy: {}".format((acc1+acc2+acc3)/3))

Average accuracy: 0.74373795761079
