In [ ]:
import zipfile
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
pwd

'/content'

In [ ]:
cd drive/MyDrive/BrainSignals/

/content/drive/MyDrive/BrainSignals




```
# Rename the unzipped dataset file to "data"
```



In [ ]:
import load_data

BATCH_SIZE =84420
# return DataSet class
data = load_data.read_data_sets(one_hot=False)

# get train data and labels by batch size
train_x, train_y = data.train.next_batch(BATCH_SIZE)
# get test data
test_x = data.test.data

# get test labels
test_y = data.test.labels

# get sample number
n_samples = data.train.num_examples
print(n_samples)

84420


In [ ]:
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)


(84420, 310)
(84420,)
(58128, 310)
(58128,)




```
# First Training
```



In [ ]:
import numpy as np
mu, sigma = 0, 0.1 
noise = np.random.normal(mu, sigma, train_x.shape)
train_x = train_x + noise

In [ ]:
from sklearn.preprocessing import LabelEncoder
import time
le = LabelEncoder()
train_y = le.fit_transform(train_y)
from xgboost import XGBClassifier
classifier1 = XGBClassifier()
classifier2 = XGBClassifier()
classifier3 = XGBClassifier()
print("Model - 1")
st=time.time()
classifier1.fit(train_x, train_y)
et=time.time()
time_elasped = (et - st)/60
print('Execution time:', time_elasped, 'min')
print("Model - 2")
st=time.time()
classifier2.fit(train_x, train_y)
time_elasped = (et - st)/60
print('Execution time:', time_elasped, 'min')
print("Model - 3")
st=time.time()
classifier3.fit(train_x, train_y)
time_elasped = (et - st)/60
print('Execution time:', time_elasped, 'min')

Model - 1
Execution time: 25.010663112004597 seconds
Model - 2
Execution time: -6.643931070963542e-06 seconds
Model - 3
Execution time: -22.52832684914271 seconds


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
print("Model - 1")
pred_y1 = classifier1.predict(test_x)
cm1 = confusion_matrix(test_y, pred_y1)
print(cm1)
acc1=accuracy_score(test_y, pred_y1)
print(acc1)
print("Model - 2")
pred_y2 = classifier2.predict(test_x)
cm2 = confusion_matrix(test_y, pred_y2)
print(cm2)
acc2=accuracy_score(test_y, pred_y2)
print(acc2)
print("Model - 3")
pred_y3 = classifier3.predict(test_x)
cm3 = confusion_matrix(test_y, pred_y3)
print(cm3)
acc3=accuracy_score(test_y, pred_y3)
print(acc3)

Model - 1
[[10892  4852  2694]
 [ 1915 16934   891]
 [  905   582 18463]]
0.7963287916322599
Model - 2
[[10892  4852  2694]
 [ 1915 16934   891]
 [  905   582 18463]]
0.7963287916322599
Model - 3
[[10892  4852  2694]
 [ 1915 16934   891]
 [  905   582 18463]]
0.7963287916322599


In [ ]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

def print_score(classifier,X_train,y_train,X_test,y_test,train=True):
    if train == True:
        print("Training results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_train,classifier1.predict(X_train))))
        print('Classification Report:\n{}\n'.format(classification_report(y_train,classifier1.predict(X_train))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_train,classifier1.predict(X_train))))
        res = cross_val_score(classifier, X_train, y_train, cv=10, n_jobs=-1, scoring='accuracy')
        print('Average Accuracy:\t{0:.4f}\n'.format(res.mean()))
        print('Standard Deviation:\t{0:.4f}'.format(res.std()))
    elif train == False:
        print("Test results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_test,classifier1.predict(X_test))))
        print('Classification Report:\n{}\n'.format(classification_report(y_test,classifier1.predict(X_test))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_test,classifier1.predict(X_test))))

def print_score(classifier,X_train,y_train,X_test,y_test,train=True):
    if train == True:
        print("Training results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_train,classifier2.predict(X_train))))
        print('Classification Report:\n{}\n'.format(classification_report(y_train,classifier2.predict(X_train))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_train,classifier2.predict(X_train))))
        res = cross_val_score(classifier2, X_train, y_train, cv=10, n_jobs=-1, scoring='accuracy')
        print('Average Accuracy:\t{0:.4f}\n'.format(res.mean()))
        print('Standard Deviation:\t{0:.4f}'.format(res.std()))
    elif train == False:
        print("Test results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_test,classifier2.predict(X_test))))
        print('Classification Report:\n{}\n'.format(classification_report(y_test,classifier2.predict(X_test))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_test,classifier2.predict(X_test))))

def print_score(classifier,X_train,y_train,X_test,y_test,train=True):
    if train == True:
        print("Training results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_train,classifier3.predict(X_train))))
        print('Classification Report:\n{}\n'.format(classification_report(y_train,classifier3.predict(X_train))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_train,classifier3.predict(X_train))))
        res = cross_val_score(classifier3, X_train, y_train, cv=10, n_jobs=-1, scoring='accuracy')
        print('Average Accuracy:\t{0:.4f}\n'.format(res.mean()))
        print('Standard Deviation:\t{0:.4f}'.format(res.std()))
    elif train == False:
        print("Test results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_test,classifier3.predict(X_test))))
        print('Classification Report:\n{}\n'.format(classification_report(y_test,classifier3.predict(X_test))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_test,classifier3.predict(X_test))))

In [ ]:
print_score(classifier1,train_x,train_y,test_x,test_y,train=False)

Test results:

Accuracy Score: 0.7988

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.59      0.69     18438
           1       0.76      0.86      0.80     19740
           2       0.83      0.93      0.88     19950

    accuracy                           0.80     58128
   macro avg       0.80      0.79      0.79     58128
weighted avg       0.80      0.80      0.79     58128


Confusion Matrix:
[[10929  4793  2716]
 [ 1775 16920  1045]
 [  755   612 18583]]



In [ ]:
print_score(classifier2,train_x,train_y,test_x,test_y,train=False)

Test results:

Accuracy Score: 0.7963

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.59      0.68     18438
           1       0.76      0.86      0.80     19740
           2       0.84      0.93      0.88     19950

    accuracy                           0.80     58128
   macro avg       0.80      0.79      0.79     58128
weighted avg       0.80      0.80      0.79     58128


Confusion Matrix:
[[10892  4852  2694]
 [ 1915 16934   891]
 [  905   582 18463]]



In [ ]:
print_score(classifier3,train_x,train_y,test_x,test_y,train=False)

Test results:

Accuracy Score: 0.7963

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.59      0.68     18438
           1       0.76      0.86      0.80     19740
           2       0.84      0.93      0.88     19950

    accuracy                           0.80     58128
   macro avg       0.80      0.79      0.79     58128
weighted avg       0.80      0.80      0.79     58128


Confusion Matrix:
[[10892  4852  2694]
 [ 1915 16934   891]
 [  905   582 18463]]



In [ ]:
print("Average accuracy: {}".format((acc1+acc2+acc3)/3))

Average accuracy: 0.7963287916322598
